name: 🐞 バグ
description: バグを報告する
title: 🐞
labels:
  - バグ
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      placeholder: なにもしてないのに壊れた！
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境
      placeholder: |
        ローカル開発環境
        Windows 10
        Google Chrome 108
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待の結果
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の結果
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: ログやスクリーンショットなど

  - type: textarea
    id: issues
    attributes:
      label: 関連チケット
      placeholder: "- #XXX"

  - type: textarea
    id: others
    attributes:
      label: その他
