name: ✅ タスク
description: タスクを起票する
title: ✅
labels:
  - タスク
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      placeholder: ○を□で△する
    validations:
      required: true

  - type: textarea
    id: initiation-condition
    attributes:
      label: 開始条件
      description: 前提タスクのチケット番号、その他のブロッカー
      placeholder: |
        - #XXX
        - #XXX

  - type: textarea
    id: completion-condition
    attributes:
      label: 完了条件
      description: 処理済み、完了となる条件
      value: "- [ ]"

  - type: textarea
    id: others
    attributes:
      label: その他
