name: CI

on:
  workflow_call:
  pull_request:
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Lint and format
      run: bun run biome:ci

    - name: Test
      run: bun run test
